# Set prefix key to Ctrl-a
unbind C-b
set-option -g prefix C-a

# Send Ctrl-a to the application running in the pane
bind C-a send-prefix

# change tmux bar color
set -g status-bg cyan

# Change index to start from 1
set -g base-index 1
setw -g pane-base-index 1

