# Set prefix key to Alt-a
unbind C-b
set-option -g prefix M-a

# Send Alt-a to the application running in the pane
bind M-a send-prefix

# change tmux bar color
set -g status-bg cyan

# Change index to start from 1
set -g base-index 1
setw -g pane-base-index 1

set -g mouse on

# Split windows horizontally and vertically
bind -n M-| split-window -h
bind -n M-- split-window -v

unbind '"'
unbind %

# Switch panes using Alt-hjkl without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
